AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: school-api/
      Handler: create.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Policies:
       - AmazonDynamoDBFullAccess
      Environment:
        Variables: 
         TABLE_NAME: !Select [1, !Split ['/', !GetAtt TestTable.Arn]] 
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /add
            Method: put
  ReadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: school-api/
      Handler: read.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Policies:
       - AmazonDynamoDBFullAccess
      Environment:
        Variables: 
         TABLE_NAME: !Select [1, !Split ['/', !GetAtt TestTable.Arn]] 
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get/{id}
            Method: get
  DeleteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: school-api/
      Handler: delete.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Policies:
       - AmazonDynamoDBFullAccess
      Environment:
        Variables: 
         TABLE_NAME: !Select [1, !Split ['/', !GetAtt TestTable.Arn]] 
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /delete/{id}
            Method: delete
  UpdateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: school-api/
      Handler: update.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Policies:
       - AmazonDynamoDBFullAccess
      Environment:
        Variables: 
         TABLE_NAME: !Select [1, !Split ['/', !GetAtt TestTable.Arn]] 
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /update/{id}
            Method: patch        
  ScanFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: school-api/
      Handler: scan.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Policies:
       - AmazonDynamoDBFullAccess
      Environment:
        Variables: 
         TABLE_NAME: !Select [1, !Split ['/', !GetAtt TestTable.Arn]] 
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get
            Method: get
  TestTable:
    Type: AWS::Serverless::SimpleTable
    TableName: test_tables
    Properties:
      PrimaryKey:
        Name: id
        Type: Number

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Create function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
